### ISSUE TITLE
[Bug]: Overrides IBM Plex font loading, forcing them to come from fonts.gstatic.com

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon-charts#1168]
### What happened?

When loading `@carbon/charts`'s CSS, I write:

```scss
@import '~@carbon/charts/styles.css';
```

following [the instructions given](https://charts.carbondesignsystem.com/?path=/story/docs-getting-started--vanilla).

However, I am observing that this CSS file includes a very large amount of CSS which is not directly related to `@carbon/charts` and in fact comes from the base Carbon library, `carbon-components`. This interferes with the rest of our application, which also loads Carbon's CSS but makes extensive use of Carbon's own fairly advanced configuration options to be more selective in what we load.

Case in point: Carbon's CSS includes a large number of CSS declarations of this form:

```css
@font-face {
  font-display: auto;
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: local("IBM Plex Sans"), local("IBMPlexSans"), url(https://fonts.gstatic.com/s/ibmplexsans/v6/zYXgKVElMYYaJe8bpLHnCwDKhdHeEw.woff) format("woff");
}
```

This causes the IBM Plex Sans font (which we use) to be loaded from a third-party provider, fonts.gstatic.com. However, our product is on-premises software with a very strict Content Security Policy. For security reasons, our customers don't want to load fonts (or any resources) from a third party host. So, we intentionally disable this behaviour using Carbon's own configuration options, and bundle the IBM Plex Sans font ourselves instead.

However, `@carbon/charts`'s CSS undoes this by incorporating those same fonts.gstatic.com font loads a second time. This is blocked by our CSP, causing a flood of console errors, and the IBM Plex font fails to load at all.

We have also had issues with `@carbon/charts` incorporating out-of-date `carbon-components` CSS which clashes with the `carbon-components` CSS we use.

So, can we make it possible to load only `@carbon/charts`'s CSS by itself, without anything else?

### Version

`@carbon/charts@0.41.103`
