### ISSUE TITLE
[Enhancement]: v11 charting token creation

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#1355]
#### Elements
- Chart title (type & color)
- Chart background
- Grid
- Grid border
- General text (type & color)
- Inverse text (type & color)
- Type on color (`white` in dark, `black` in light) - currently happening in treemap
- Border on color (`white` in dark, `black` in light) - currently happening in heatmap when hovering a cell

#### Axis
- Lines
- Tick (same as general text)
- Title (same as chart title)

#### Skeleton
- Grid skeleton
- Grid border skeleton
- Pie skeleton

#### Zooming
- Non-focal fill (currently happening in circlepack)
- Non-focal border (currently happening in circlepack)

## TODO
- [ ] add all the `@if matches` tokens as well
### Things to update in charts
- Switch over the heatmap shadows to the Carbon shadow token https://carbon-elements.netlify.app/themes/examples/preview-v11/#shadow

## Questions

Tokens that are missing

./styles/components/_ruler.scss
```scss
@if $background == map-get($theme--g90, 'ui-background') {
	stroke: $white-0;
} @else if
	$background ==
	map-get($theme--g100, 'ui-background')
{
	stroke: $white-0;
} @else {
	stroke: $black-100;
}
```

skeleton-lines.scss
```scss
@if $theme == $theme--g10 {
	fill: $layer-01;
} @else if $theme == $theme--g90 {
	fill: $gray-100;
} @else {
	fill: $background;
}
```

skeleton.scss
```scss
@if $theme == $theme--g10 {
	fill: $layer-01;
} @else if $theme == $theme--g90 {
	fill: $gray-100;
} @else {
	fill: $background;
}
```

tooltip.scss
```scss
@if ($theme == $theme--g90) or
	($theme == $theme--g100)
{
	fill: white;
} @else {
	fill: black;
}
```

```scss
@if $theme == $theme--g90 {
	border-bottom: 1px solid $layer-01;
} @else if $theme == $theme--g100 {
	border-bottom: 1px solid $border-strong-01;
} @else {
	border-bottom: 1px solid $layer-accent-01;
}
```

bullet.scss
```scss
@if ($theme == $theme--g90) or
	($theme == $theme--g100)
{
	fill: $gray-90;
	stroke: $gray-60;
} @else {
	fill: $gray-10;
	stroke: $gray-50;
}
```

```scss
@if ($theme == $theme--g90) or
($theme == $theme--g100)
{
fill: $gray-80;
stroke: $gray-60;
} @else {
fill: $gray-20;
stroke: $gray-50;
}
```

```scss
@if ($theme == $theme--g90) or
($theme == $theme--g100)
{
fill: $gray-70;
stroke: $gray-60;
} @else {
fill: $gray-30;
stroke: $gray-50;
}
```

```scss
@if ($theme == $theme--g90) or
	($theme == $theme--g100)
{
	stroke: #fff;
} @else {
	stroke: #000;
}
```

```scss
@if ($theme == $theme--g90) or
	($theme == $theme--g100)
{
	stroke: #000;
} @else {
	stroke: #fff;
}
```
