### ISSUE TITLE
[Bug]: Generated styles.css should use CSS custom properties for font-family

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1638]
### Name

Nate Stuyvesant

### Are you an IBM employee?

- [ ] Yes

### Summary

Currently, the generated styles.css references `IBM Plex Sans Condensed` or `IBM Plex Sans` in 12 different selectors and then in 24 CSS custom properties.

The problem is that the 12 selectors use IBM Plex faces directly rather than using any of the defined CSS custom properties. If users are loading styles as CSS, they will have to override the 12 selectors individually to change the font.

Here are the 12 selectors in the generated styles.css where the font is set without custom CSS properties:
```css
.cds--cc--axes g.axis g.tick text {
  fill: var(--cds-text-secondary, #525252);
  font-family: 'IBM Plex Sans Condensed', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
}

.cds--cc--axes g.axis .axis-title {
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  font-weight: 600;
  fill: var(--cds-text-primary, #161616);
}

.cds--cc--title p.title {
  color: var(--cds-text-primary, #161616);
  font-size: 16px;
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  font-weight: 600;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 15px;
}

.cds--cc--tooltip {
  background-color: var(--cds-layer-02, #ffffff);
  pointer-events: none;
  transition-timing-function: cubic-bezier(0.4, 0.14, 0.3, 1);
  display: inline;
  visibility: visible;
  box-shadow: 0 1px 6px 0 rgba(0, 0, 0, 0.2);
  position: absolute;
  word-wrap: break-word;
  z-index: 1059;
  font-family: 'IBM Plex Sans Condensed', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  transition: visibility 0s linear 0.1s, opacity 0.1s;
}

.cds--cc--threshold--label {
  background-color: #fa4d56;
  pointer-events: none;
  transition: opacity 0.1s;
  transition-timing-function: cubic-bezier(0.4, 0.14, 0.3, 1);
  display: inline;
  box-shadow: 0 1px 6px 0 rgba(0, 0, 0, 0.2);
  position: absolute;
  word-wrap: break-word;
  z-index: 1059;
  font-family: 'IBM Plex Sans Condensed', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  color: var(--cds-text-primary, #161616);
  line-height: 16px;
  font-size: 12px;
  padding: 4px;
  min-width: 20px;
}

.cds--cc--card-node {
  display: flex;
  position: relative;
  background-color: var(--cds-layer-01, #f4f4f4);
  z-index: 1;
  box-sizing: border-box;
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  width: 100%;
  height: 100%;
  padding: 1rem 0.5rem;
  border-left: 0.25rem solid var(--cds-border-inverse, #161616);
}

.cds--cc--card-node--button {
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  text-align: left;
  width: 100%;
}

.cds--cc--shape-node {
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: var(--cds-layer-01, #f4f4f4);
  box-sizing: border-box;
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  width: 100%;
  height: 100%;
  position: relative;
}

.cds--cc--shape-node--button {
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  text-align: left;
  width: 100%;
}

.cds--cc--chart-wrapper {
  font-family: 'IBM Plex Sans Condensed', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
}

.cds--cc--chart-wrapper g.gauge-numbers text.gauge-value-number {
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
  font-weight: 300;
}

.cds--cc--chart-wrapper text.meter-title,
.cds--cc--chart-wrapper text.percent-value {
  font-size: 16px;
  font-family: 'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif;
}
```

In the original SCSS, all of these 12 examples use the `font-family()` mixin. Here are two examples in packages/core/scss/_type.scss
```scss
@use '@carbon/styles/scss/type' as *;

g.gauge-numbers text.gauge-value-number {
  font-family: font-family('sans');
  font-weight: 300;
  }
  
text.meter-title,
text.percent-value {
  font-size: $base-font-size;
  font-family: font-family('sans');
}
```

### Justification
These values should be controlled by CSS custom properties that are initially set by the `font-family` SCSS mixin rather than set explicitly for each selector.
